export const LOGIN = "LOGIN";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_ERRORS = "AUTH_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const OTP_SENT = "OTP_SENT";
export const OTP_SENT_FAILED = "OTP_SENT_FAILED";
export const OTP_VERIFIED = "OTP_VERIFIED";
export const OTP_VERIFICATION_FAILED = "OTP_VERIFICATION_FAILED";
export const LOGOUT = "LOGOUT";

export const REGISTER_USER = "register_user";
export const REGISTER_USER_SUCCESSFUL = "register_user_successfull";
export const REGISTER_USER_FAILED = "register_user_failed";

export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_ERRORS = "PROFILE_ERRORS";
export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
export const SHOW_EDIT_UPI_MODAL = "SHOW_EDIT_UPI_MODAL";
export const HIDE_EDIT_UPI_MODAL = "HIDE_EDIT_UPI_MODAL";

export const DOWNLOAD_QR = "DOWNLOAD_QR";
export const DOWNLOAD_QR_FAILED = "DOWNLOAD_QR_FAILED";
export const GENERATE_REPORTS = "GENERATE_REPORTS";
export const GENERATE_REPORTS_SUCCESS = "GENERATE_REPORTS_SUCCESS";
export const GENERATE_REPORTS_FAILED = "GENERATE_REPORTS_FAILED";
export const FETCH_REPORTS = "FETCH_REPORTS";
export const FETCH_REPORTS_FAILED = "FETCH_REPORTS_FAILED";
export const SETTLEMENT_LOADING = "SETTLEMENT_LOADING";
export const FETCH_SETTLEMENT_TRANSACTIONS = "FETCH_SETTLEMENT_TRANSACTIONS";
export const FETCH_SETTLEMENT_TRANSACTIONS_FAILED =
  "FETCH_SETTLEMENT_TRANSACTIONS_FAILED";
export const ADD_BANK_DETAILS = "ADD_BANK_DETAILS";
export const ADD_BANK_DETAILS_FAILED = "ADD_BANK_DETAILS_FAILED";
export const FETCH_BANK_DETAILS = "FETCH_BANK_DETAILS";
export const FETCH_BANK_DETAILS_FAILED = "FETCH_BANK_DETAILS_FAILED";
export const CHANGE_DEFAULT_BANK = "CHANGE_DEFAULT_BANK";
export const CHANGE_DEFAULT_BANK_FAILED = "CHANGE_DEFAULT_BANK_FAILED";

export const ORDER_TRANSACTIONS_LOADING = "ORDER_TRANSACTIONS_LOADING";
export const FETCH_ORDER_TRANSACTIONS = "FETCH_ORDER_TRANSACTIONS";
export const FETCH_ORDER_TRANSACTIONS_FAILED =
  "FETCH_ORDER_TRANSACTIONS_FAILED";
export const FETCH_SINGLE_ORDER = "FETCH_SINGLE_ORDER";
export const FETCH_SINGLE_ORDER_FAILED = "FETCH_SINGLE_ORDER_FAILED";
export const CHANGE_ORDER_STATUS = "CHANGE_ORDER_STATUS";
export const CHANGE_ORDER_STATUS_FAILED = "CHANGE_ORDER_STATUS_FAILED";

export const SUPPORT_LOADING = "SUPPORT_LOADING";
export const ADD_TICKET = "ADD_TICKET";
export const ADD_TICKET_FAILED = "ADD_TICKET_FAILED";
export const GET_TICKETS = "GET_TICKETS";
export const GET_TICKETS_FAILED = "GET_TICKETS_FAILED";
export const GET_TICKET = "GET_TICKET";
export const GET_TICKET_FAILED = "GET_TICKET_FAILED";
export const ADD_TICKET_CONVERSATION = "ADD_TICKET_CONVERSATION";
export const ADD_TICKET_CONVERSATION_FAILED = "ADD_TICKET_CONVERSATION_FAILED";

export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";
